# board: ['slimboard']
# shield: ['slimboard_left', 'slimboard_right', 'slimboard_dongle']
include:
  - board: slimboard
    shield: slimboard_left
  - board: slimboard
    shield: slimboard_right
  - board: slimboard
    shield: slimboard_dongle
  - board: slimboard
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
