include:
  - board: seeed_xiao_nrf52840
    shield: slimboard_left
    name: slimboard_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeed_xiao_nrf52840
    shield: slimboard_right
    name: slimboard_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeed_xiao_nrf52840
    shield: slimboard_dongle
    name: slimboard_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

  - board: seeed_xiao_nrf52840
    shield: settings_reset
    name: slimboard_settings_reset
